### ISSUE TITLE
can not custom root package

### ISSUE THREAD

**Issue by oojdon** [javalite/activeweb#233] opened 2015-07-21 07:15 UTC
in Router,hard code the controller must start with app.controllers, So that I can not custom the controller package via activeweb.properties, thanks

```
 String className = controllerClass.getName();
   if (!className.startsWith("app.controllers")) {
            throw new ControllerException("controller must be in the 'app.controllers' package");
       }
```

**Comment by ipolevoy** [comment] 2015-07-21 16:04
@oojdon , this is not a bug, bur rather a framework requirement. Please see this: http://javalite.io/structure_of_activeweb_project#location-of-controllers

closing  this as a non-issue

**Closed by ipolevoy** 2015-07-21 16:04 UTC
