### ISSUE TITLE
Performance improvements based in Web Framework Benchmarks

### ISSUE THREAD

**Issue by ericbn** [javalite/activeweb#197] opened 2015-01-09 21:39 UTC
Improve performance for all [Web Framework Benchmarks](http://www.techempower.com/benchmarks/) tests.

**Comment by ericbn** [comment] 2015-01-09 21:49
### Test fortunes

A profiling of the test (running from an unit test) showed it spends 43.4% - 39.9% of the time with `freemarker.*` methods.

In this test, optimization in ActiveWeb can be achieved using a faster alternative to Freemarker.

The ActiveWeb method with greater self time is `RequestBuilder.submitRequest()` (1.7% - 2%), followed by `ControllerRunner.executeAction()` (0.8%) and `Router.getControllerPath()` (0.7%), so ActiveWeb looks "lite" enough here!  :- )

**Comment by ipolevoy** [comment] 2015-01-09 22:14
yeah, my previous tests also pointed to the FreeMarker before. 
The method `RequestBuilder.submitRequest()` is irrelevant because it is used in tests only. 
Replacing FreeMarker with something else will not be easy, although ActiveWeb has a pluggable architecture. The question is what to replace with? Besides, JavaLite sites are really fast, and FreeMarker in real applications performs really well.  This is why I do not think   that making any changes in AJ will help this test. 

thoughts?

**Comment by ipolevoy** [comment] 2015-01-09 22:19
however. We can look at proper configuration of FreeMarker (not sure it is the most optimized) with caching/compiling - etc. See http://freemarker.org/docs/app_faq.html  paragraph 25

**Comment by ipolevoy** [comment] 2015-01-12 02:16
I decided to build a very simple and fast templating framework called Templator  (in the same spirit of not depending on others). I'm 80% done and will get the http://www.techempower.com/benchmarks/  example on Templator  by end of week. Can  you please do a base test now with timing, etc. so that when a new one comes out, we will perform a another  test and compare performance of Templator vs FreeMarker? 

tx

**Comment by ipolevoy** [comment] 2015-01-12 02:35
Please, take a look: https://github.com/javalite/activeweb/tree/master/javalite-templator 
code is rough around the edges, but I think this will be super fast.

**Comment by ericbn** [comment] 2015-01-12 11:58
Great! I'll finish profiling all the  [Web Framework Benchmarks](http://www.techempower.com/benchmarks/) tests and post them here.

**Comment by ericbn** [comment] 2015-01-12 21:49
### Test fortunes

Unit test with loop running for one minute. Spent 44.9% in `com.mysql.*` (JDBC driver) methods, and 38.6% in `freemarker.*` methods.

![fortunes](https://cloud.githubusercontent.com/assets/4120606/5711276/4514108a-9a90-11e4-9746-413294c58376.png)

----------

### Test plaintext

Unit test with loop running for one minute. Freemarker was initialized, even not being used to render the response (as controller used `respond()` method). 

![plaintext](https://cloud.githubusercontent.com/assets/4120606/5711020/6294d876-9a8e-11e4-8738-a18643badab2.png)

### Test json

Unit test with loop running for one minute. Spent 70.1% in `com.fasterxml.*` (Jackson) methods. Freemarker was initialized, even not being used to render the response. 

![json](https://cloud.githubusercontent.com/assets/4120606/5711678/7af7f858-9a93-11e4-991b-f656fa5f0259.png)

**Comment by ipolevoy** [comment] 2015-01-13 01:44
Interesting. Lets take care of FreeMarker, than lets take care of Jackson. Actually, I was hoping it was faster..

**Comment by ipolevoy** [comment] 2015-01-13 05:38
I pushed a new version that uses JavaLite Templator. Interesting what the results are. 
Templator has absolutely minimum features. Only to satisfy this test for now

**Comment by ipolevoy** [comment] 2015-01-13 05:40
Please, see commit:
https://github.com/javalite/FrameworkBenchmarks/commit/17591dbbc7b78686d92d2a5e8469b33de5f36698

I hope it is an improvement over FreeMarker and Jackson.

**Comment by ericbn** [comment] 2015-01-13 14:10
Shouldn't we release before moving further with the optimizations and new implementations?

I'll post more test of the current implementation, then I'll test the updated one with Templator.

**Comment by ipolevoy** [comment] 2015-01-13 14:16
Templator will require a lot more work. This is just to see if the concept is right. We can release now, or later, and note that Templator is work in progress. No commercial code depends on Templator, and as long as we do not touch anything else, I think it is OK to work on Templator and release at the same time. 
The template parser in Templator is crap, and needs to be redone, but it will not affect performance, since by design parsing happens only once.
I'm curious about the difference just to see if it makes sense to continue in  this direction. Also, I plan to release this weekend. 
thoughts?

**Comment by ericbn** [comment] 2015-01-13 16:21
Great, I agree! I'll be happy to help with parsing and generation in Templator. Let's see how it performs now...

I was also thinking about moving the `Model.toJson()` and `toXml()` methods to another class (say `DataTransferObject` or something like this) and make `Model` extend it. So we can use JSON and XML serialization outside models. The concrete `DataTransferObject` would also delegate to a map, with the added feature of JSON and XML serialization. This will be a faster implementation than using templates to generate the output. We would also "lighten" our current `Model` class. Plans for 1.6 version maybe. What do you think?

**Comment by ericbn** [comment] 2015-01-13 17:54
EC2 tests with 3 VirtualBox servers environment (app, client, db) - before Templator

	|gemini	|activeweb	|activeweb/gemini %
-----|-----|-----|-----
fortune	|32797	|2486	|7.6
plaintext	|145432|	111809	|76.9
db	|43590	|17967	|41.2
update	|22619	|2250	|9.9
json	|109808	|74210	|67.6
query	|28520	|2230	|7.8

**Comment by ipolevoy** [comment] 2015-01-13 18:32
is bigger number better or worse?

**Comment by ericbn** [comment] 2015-01-13 18:47
Bigger % number means closer to gemini, so better. I can't push to javalite/FrameworkBenchmarks. Is it my side or do I miss any permission at the repo?

**Comment by ipolevoy** [comment] 2015-01-13 18:49
you should be able to push to my  fork: https://github.com/javalite/FrameworkBenchmarks
I'm still confused regarding percentage. Are we better than gemini?

**Comment by ipolevoy** [comment] 2015-01-13 18:49
I mean faster?

**Comment by ericbn** [comment] 2015-01-13 18:51
No, we are never better than gemini. 100% would mean equal performace. 50% means we are half speed. 200% would mean we are double speed.

**Comment by ericbn** [comment] 2015-01-13 18:52
Oh, and the absolute number are total requests -- forgot to mention that!

**Comment by ipolevoy** [comment] 2015-01-13 18:57
hm, than the numbers are not the best. Why did you pick gemini? Is it a leader in the test?

**Comment by ipolevoy** [comment] 2015-01-13 18:57
also, are you running the latest code with templator?

**Comment by ericbn** [comment] 2015-01-13 20:19
From what I understood, gemini is implemented by the same guys responsible for TechEmpower/FrameworkBenchmarks. But undertow performs better in EC2 environment, so I'll redo tests comparing with undertow later.

One test failed with Templator:

>   FAIL for http://172.16.0.16:8080/activeweb/fortunes
>     `<tr><td>11</td><td><script>alert(&quot;This should not be displayed in a browser alert box.&quot;);</script></td></tr>` should be `<tr><td>11</td><td>&lt;script&gt;alert(&quot;This should not be displayed in a browser alert box.&quot;);&lt;/script&gt;</td></tr>`

**Comment by ipolevoy** [comment] 2015-01-13 20:21
yes, this is a known issue. I just want to see how it stacks up against best

**Comment by ericbn** [comment] 2015-01-13 20:28
Cannot push to javalite/FrameworkBenchmarks, created a pull request: https://github.com/javalite/FrameworkBenchmarks/pull/1

Test fortunes is FAILING now, so we'll not have complete results. Just need to implement replaces for `<` -> `&lt;` and `>` -> `&gt;`.

**Comment by ipolevoy** [comment] 2015-01-13 20:34
I know the test is failing, just need to escape. But this will not prevent from our internal test, right? 
Not sure why you cannot push to repo, you are a member of the organization.

**Comment by ericbn** [comment] 2015-01-13 21:15
New results with Templator: total requests, activeweb vs. gemini rate now and before Templator

	|gemini	|activeweb	|activeweb/gemini %|before
-----|-----|-----|-----|-----
update	|22480	|12132	|54.0	 | 9.9
json	|110985	|71611|	64.5	 | 67.6
query	|29520|	15797	|53.5 	 | 7.8

Templator performed way better than Freemarker! Notice how the three worse results we had (fortune, update and query) were the ones that used Freemarker. It didn't perform better than Jackson though. My suggestion: https://github.com/javalite/activeweb/issues/197#issuecomment-69771200

I'll run the unit tests with profiling now.

**Comment by ipolevoy** [comment] 2015-01-13 21:19
Great!

However the current json  implementation does not use Jackson anymore. It is also not using toJson(). Not sure I'm following you on the refactoring. The Model.toJson() is only quick and dirty prototypes. You would not use that in a real project, right?

**Comment by ipolevoy** [comment] 2015-01-13 21:24
sorry for a stupid question, but how do U merge a PL: https://github.com/javalite/FrameworkBenchmarks/pull/1
I have no options for this!

**Comment by ericbn** [comment] 2015-01-13 21:26
At the end of the page there should be a button to accept it. My page says I don't have permission to do it: "
This pull request can be automatically merged by project collaborators. Only those with write access to this repository can merge pull requests."

**Comment by ipolevoy** [comment] 2015-01-13 21:31
thanks merged

**Comment by ipolevoy** [comment] 2015-01-13 21:32
you are a member of javalite org, not sure why you could not do this

**Comment by ericbn** [comment] 2015-01-13 22:05
### About the JSON discussion

How it was/is serialized in activeweb benchmark tests that expect JSON response:

Test | Before Templator|Now
-----|-----|-----
db|Model.toJson()|Model.toJson()
fortunes|Freemarker|Templator
json|Jackson|Templator
queries|Freemarker|Templator
updated|Freemarker|Templator

So Model.toJson() is being used. Templator is [not faster](https://github.com/javalite/activeweb/issues/197#issuecomment-69821475) than Jackson.

I changed the db test implementation to use Jackson, take a look at the results:

	|gemini	|activeweb	|% with Jackson | % before with Model.toJson()
-----|-----|-----|-----|-----
db	|44427	|10154	|22.9 	|[41.2](https://github.com/javalite/activeweb/issues/197#issuecomment-69787855) 

Model.toJson() is way faster than Jackson (Jackson uses reflection in the first place). Model.toJson() works and it simpler to use than Jackson or any template mechanism (no extra code), so why not use it in production? Anyway, it is sure a way to perform better in the tests! 

And I'll be really happy to improve our toJson() implementation so you think it is not quick and dirty anymore.

So these are my motivations for the refactoring.

PS: Will post the updated profiling tests tomorrow!

**Comment by ipolevoy** [comment] 2015-01-13 22:19
looks like activeweb is completely gone after pull request :) What happened?

**Comment by ipolevoy** [comment] 2015-01-13 22:21
found it, never mind

**Comment by ipolevoy** [comment] 2015-01-13 22:34
I see that DB is using Model.toJson(). My hunch is that  Model.toJson() and Tempator would be so fast, almost as fast as anything else, since they are not doing much. Templator pre-parses a template and simply writes chunks of Strings to writer. How is gemini so fast?

**Comment by ericbn** [comment] 2015-01-14 14:13
[Gemini](https://groups.google.com/forum/#!topic/framework-benchmarks/p3PbUTg-Ibk) is not open source. If you take a look at [their test code](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/gemini/Source/hello/home/handler/HelloHandler.java#L43), they have their own `json()` and `EntityStore` implementations.

I insist we should have an specific implementation for JSON serialization, which will always be faster an simpler to use than templates, and for models that's our `Model.toJson()`. For other objects that are not models, one should be able to do `new DataTransferObject().set("message", "Hello, World!").toJson()` to get `"{"message":"Hello, World!"}"` for example...

**Comment by ipolevoy** [comment] 2015-01-14 14:21
Got it. I think you are right about moving implementations of toJson() and toXml() out of model into a separate utility class, an using that class in this test. `DataTransferObject` is a terrible name though, we need to come up with a better one

**Comment by ericbn** [comment] 2015-01-14 14:48
I agree 100% `DataTransferObject` is an horrible name!  :- )  We'll come up with something better... suggestions?

**Comment by ericbn** [comment] 2015-01-14 15:10
Profiling results using Templator:

### Test fortunes

Unit test with loop running for one minute. We went from 9,920 to 23,040 requests in one minute! Spent 61.1% in com.mysql.* (JDBC driver) methods, and 6.9% in `org.javalite.templator.*` methods (vs. 38.6% in `freemarker.*` methods as before). Huge improvement!

Spent 10.1% of the time in `Configuration.getFreeMarkerConfig()` though (it tried to find it everytime again as it didn't exist), this is one of the hard-wires it still has with Freemarker...

![fortunes](https://cloud.githubusercontent.com/assets/4120606/5740754/999fec74-9bed-11e4-8836-8d5a60a03f8c.png)

**Comment by ericbn** [comment] 2015-01-14 16:49
Tests with undertow included, absolute values are number of total requests.

While gemini is based on Servlet and its tests run on [Resin](http://caucho.com/) server, as well as ActiveWeb, on the other hand, [Undertow](http://undertow.io/) is a complete web server with its own API -- so, hard to beat! We should be very happy when we get closer to gemini...

 |undertow|gemini|activeweb|undertow %|gemini %|activeweb %
-----|-----|-----|-----|-----|-----|-----
fortune|32827|34703||94.6|100.0|
plaintext|801296|145114|107710|100.0|18.1|13.4
db|46835|42670|9905|100.0|91.1|21.1
update|27675|22174|12058|100.0|80.1|43.6
json|141165|111530|71023|100.0|79.0|50.3
query|39969|28832|15780|100.0|72.1|39.5

**Comment by ipolevoy** [comment] 2015-01-14 17:25
looks like we are loosing the most in db. In all other categories we are about twice as slow. Is there a reason fortunes category is missing? 
What would profiling of db produce?

**Comment by ipolevoy** [comment] 2015-01-14 17:29
The new class for formatting JSON and XML needs to be simply called Formatter  and be in javalite-common package. It needs to look something like this:

```
public class Formatter{
  public static void toJSON(Map data, boolean pretty, Writer writer, String ... attributes);
  public static void toXML(Map data, boolean pretty, Writer writer, String ... attributes);
}
```
If attribute are missing, include all, if specified, only include those. 

and potentially a couple of more flags. Go ahead and make this change on master. We are not using these methods in projects.

Making sense?

**Comment by ipolevoy** [comment] 2015-01-14 17:31
getFreeMarkerConfig() needs to be fixed! I will look into that

**Comment by ericbn** [comment] 2015-01-14 18:49
Fortunes is missing because the test fails and the testrunner does not count that.

I'll go ahead with the Formatter.

**Comment by ipolevoy** [comment] 2015-01-15 06:49
I started looking at fixing the fortunes test, and found this: https://commons.apache.org/proper/commons-lang/javadocs/api-2.6/org/apache/commons/lang/StringEscapeUtils.html. 

So... do I just use the commons-lang3 library as a dependency or borrow a bit of code from it into AW? I'm split :(

**Comment by ericbn** [comment] 2015-01-15 10:59
We already have our `escapeJson()` hard coded into `Model.toJson()`:

    return str.replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\b", "\\b")
            .replace("\f", "\\f")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t");

The lightest implementation of `escapeHtml()` can be just

    return str.replace("&", "&amp;")
            .replace("\"", "&quot;")
            .replace("'", "&apos;") 
            .replace("<", "&lt;")
            .replace(">", "&gt;");

And I would start with this for our `StringEscapeUtil`. This can even replace the `XmlEntities` class imported from Apache Commons in our org.javalite.common package. The `escapeXml()` is just a `return escapeHtml(str);`

**Comment by ipolevoy** [comment] 2015-01-15 13:20
awesome, I forgot about this class :)

**Comment by ipolevoy** [comment] 2015-01-15 14:32
fortunes test should be working now

**Comment by ericbn** [comment] 2015-01-15 21:03
### Tests update

Had to change the `Escape.html()` implementation for the testrunner to accept it. It was escaping high unicode chars too, and the test wasn't accepting that.

Unfortunately there is a variation in the results in each run, if you compare it to the [last run](https://github.com/javalite/activeweb/issues/197#issuecomment-69948017).

 |undertow|gemini|activeweb|undertow %|gemini %|activeweb %
-----|-----|-----|-----|-----|-----|-----
fortune|32647|34287|13457|95.2|100.0|39.2
plaintext|796480|145606|105567|100.0|18.3|13.3
db|45927|41696|9927|100.0|90.8|21.6
update|26503|21793|11972|100.0|82.2|45.2
json|138426|108199|69815|100.0|78.2|50.4
query|40289|26819|14016|100.0|66.6|34.8

**Comment by ipolevoy** [comment] 2015-01-15 21:35
looks like the biggest time lost in the "db" test. Can you profile that and see where we spend the most time?

**Comment by ipolevoy** [comment] 2015-01-15 21:35
did you push `Escape.html()` code change?

**Comment by ericbn** [comment] 2015-01-15 23:30
No, not yet.

**Comment by ericbn** [comment] 2015-01-16 17:48
Updated profiling:

### Test fortunes

Unit test with loop running for one minute. We went from 23,040 to 32,493 requests in one minute! Spent 69.4% in `com.mysql.*` (JDBC driver) methods, 9.8% in `org.javalite.activeweb.*`, 7.5% in `org.javalite.templator.*` methods, and 6% in `org.javalite.activejdbc.*` methods.

`MergeToken.process()` takes 4.4% of the total time, it is the strongest candidate for optimizations. It spent 2.2% of the time reading the template file 32,493 times. There's room for improvement here too. 

![fortunes - templator](https://cloud.githubusercontent.com/assets/4120606/5779668/d7b5de8e-9d8b-11e4-910a-dcdfab788691.png)

----------

### Test db

Unit test with loop running for one minute. First time it's run. Spent 84.8% in `com.mysql.*` (JDBC driver) methods, 9.5% in `org.javalite.activeweb.*`, 3.3% in `org.javalite.activejdbc.*` methods, and 0.3% in `org.javalite.templator.*` methods.

Templator was initialized even not being used.

![db](https://cloud.githubusercontent.com/assets/4120606/5781102/138931a8-9d97-11e4-9dd4-79cbb54518e7.png)

**Comment by ericbn** [comment] 2015-01-20 10:44
@ipolevoy, one of the factors that affected the **db** test performance is how `Model.findById()` is implemented. I basically removed the `limit(1)` and changed it to make sure it only fetched the first row and look at the results:

	|undertow	|gemini|activeweb|undertow %|gemini %|activeweb %
-----|-----|-----|-----|-----|-----
db|45927|41696|19017|100.0|90.8|41.4 (was 21.6)

MySQL takes more time to process a query with a `LIMIT 1` clause. I'll finish my correction and post it soon.

**Comment by ipolevoy** [comment] 2015-01-21 05:17
@ericbn , I'm getting confused in this thread. When you attach images, only attach 20 or so lines. Also, can you please post the latest tests for all and for each test, where we spend the most time. I want to see the "lowers hanging fruit". 
Also, where are your changes for the `LIMIT 1`?

**Comment by ericbn** [comment] 2015-01-21 10:29
Yeah, indeed, this thread got too long. I'll try to create a wiki page and update it with the profiling results, and with smaller images too...  ;- )

I didn't push my changes yet.

**Comment by ericbn** [comment] 2015-01-21 14:53
I'll push the changes for the `LIMIT 1` in my fork, ok?

**Comment by ipolevoy** [comment] 2015-01-21 15:59
yep, your fork :)

**Comment by ipolevoy** [comment] 2015-02-25 05:26
@ericbn, they are going to run a round 10 in mid-March. We should see what else we can do. I have made some improvements in the Templator, but the biggest issue is to add scripting logic to it, like:

```
<#if (a && b) != c >
data
</#if>
```
some exists, and you can see tests starting here and through the end of spec: https://github.com/javalite/activeweb/blob/master/javalite-templator/src/test/java/org/javalite/templator/TemplateSpec.java#L295

however, this is a primitive implementation and does not support  more than two operands with one operator :)

So... should we submit this to benchmark?

**Comment by ericbn** [comment] 2015-02-25 13:01
@ipolevoy, we don't need scripting logic for the test requirements. So I think it is okay to use the last 1.11 release version.

Somethings I tried and my own profiling gave me ambiguous results:
* Find first without LIMIT 1 in the query: Not sure this improves performance for all databases (or any in all environments). 
* JSON serialization: The [all-purpose toJson method](https://github.com/javalite/activejdbc/issues/341) got too complex. Using Templator to generate JSON output also was not faster than using Jackson. One last thing I thought I want to try is making Model extend Map and use Jackson to serialize it. My idea is, since it will be serializing a Map, it will not use reflection, which will be a lot faster, behaving almost like the [all-purpose implementation](https://github.com/javalite/activejdbc/issues/341) I suggested before.

As they allow us to create many implementations for the same test, maybe we can create multiple test and let their results give us more concrete evidences. For example, we can create a test that serializes to JSON using Templator and another that uses Jackson.

What do you think?

**Comment by ericbn** [comment] 2015-02-25 13:43
Found a benchmark of serializers at https://github.com/eishay/jvm-serializers/wiki

**Comment by ipolevoy** [comment] 2015-02-25 15:30
@ericbn , how about we submit what we have? Making any code to perform faster also makes it uglier. Since ours is a product and not a project, we need to find balance. We have improved a lot with Templator, didn't we?

**Comment by ipolevoy** [comment] 2015-02-25 15:36
Current results from found 10: http://www.techempower.com/benchmarks/previews/round10

* Json Serialization: 216,718
* Single query:  88,692	
* Multiple queries: 6,574	
* Fortunes: 3,670
* Data updates: 885
* Plain text: 323,682

**Comment by ericbn** [comment] 2015-02-25 15:50
I'm suggesting changes in our FrameworkBenchmarks code, not in the ActiveWeb or ActiveJDBC code.

I suppose these results are from an old version of our FrameworkBenchmarks code, as they didn't accept [my pull request](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1308) yet.

**Comment by ipolevoy** [comment] 2015-02-25 15:59
@ericbn , sorry I'm confused - if we are to make changes in our FrameworkBenchmarks code, not in the ActiveWeb or ActiveJDBC code, than this is not a valid test, correct? In other words, people seeing test and thinking they will get certain level of performance will chose JL, but will not get that performance :) ?

**Comment by ericbn** [comment] 2015-03-10 20:43
@ipolevoy, these are the preliminary results with the latest test version (using release versions of activeweb and activejdbc) at https://www.techempower.com/benchmarks/previews/round10:

Test | Round 9 was | Round 10 was (https://github.com/javalite/activeweb/issues/197#issuecomment-75981933) | Round 10 now (using Templator* or Model.toJson()**) | Round 10 now (using Jackson)
--- | --- | --- | --- | ---
Json Serialization | 220,022 | 216,718 | 71,649* | 364,520
Single query | 92,210 | 88,692 | 101,535** | 102,030
Multiple queries | 5,926 | 6,574 | 6,563* | 5,846
Fortunes | 3,759 | 3,670 | 8,527* | 
Data updates | 1,305 | 885 | 972* | 914
Plain text | 339,627 | 323,682 | 321,770

Two first columns are from last version of test (running on round 9 and 10-preview). While Templator did a better job than Jackon in "Data updates" and "Multiple queries", it really sucked in "Json Serialization" test.

**Closed** 2019-10-03 22:25 UTC
