### ISSUE TITLE
Next filter executed after in previous filter was created response.

### ISSUE THREAD

**Issue by yanchevsky** [javalite/activeweb#330] opened 2017-03-01 16:37 UTC
Next filters should be ignored if current filter create HTTP response.

**Comment by ipolevoy** [comment] 2017-03-01 21:28
@yanchevsky so.. this also means that execution of all filters and all controllers downstream should be ignored, right?

**Comment by ipolevoy** [comment] 2017-03-02 14:33
if a filter used the `respond()` method, the chain of calls need to stop, including controller. 
The `after()` methods need to be executed in the reverse order as usual.

**Comment by ipolevoy** [comment] 2018-08-29 17:57
this might be an outdated thinking after : https://github.com/javalite/activeweb/issues/356...

**Comment by mppfiles** [comment] 2019-02-15 11:09
I think both approaches are right, and not mutually exclusive.
Maybe it would be cleaner to throw some custom exception that triggers the interruption of the downstream filters, and let each one of them to handle such exception if needed.

**Comment by mppfiles** [comment] 2019-02-15 13:03
Maybe we can leverage the concept of filter groupings, to achieve this feature... the purpose of them is not so clear...

**Comment by ipolevoy** [comment] 2019-02-15 18:56
I'm not really sold on this idea. Currently if the filter uses a `respond()` method,  that effectively breaks the execution of downstream  filters. Also, what if the other filter must be called to execute `after()` in order to close a resource allocated in the `before()`? 
In other words, what is the problem we are trying to solve here?

**Comment by mppfiles** [comment] 2019-02-15 20:29
@ipolevoy you are correct. On the latest version of AW this works as intended. This issue is rather old, and I hit it because I'm on java7 branch. I guess you may close this one.

**Comment by ipolevoy** [comment] 2019-02-15 20:34
:+1:

**Closed by ipolevoy** 2019-02-15 20:34 UTC
