### ISSUE TITLE
persian or arabic text problem

### ISSUE THREAD

**Issue by hra1368** [javalite/activeweb#347] opened 2017-06-07 19:13 UTC
when type persian/arabic text in ftl file then see incorrect text in browser. 
defualt_layout.ftl
<#setting url_escaping_charset='utf-8'>

web.xml:
```
        <init-param>
            <param-name>encoding</param-name>
            <param-value>UTF-8</param-value>
        </init-param>
```
set above config also.
please advise me. thanks

**Comment by ipolevoy** [comment] 2017-06-07 19:30
@hra1368 please include what you typed and screenshot of the page, as well as source of generated HTML

**Comment by ipolevoy** [comment] 2017-06-08 02:44
duplicate of https://github.com/javalite/activeweb-simple/issues/4

**Closed by ipolevoy** 2017-06-08 02:44 UTC
